version: "3"
services:
  bot:
    image: ghcr.io/adrianvillanueva997/telegrambot_reminder:latest
    container_name: telegrambot_reminders
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - 2112
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - bots
networks:
  bots:
    external: true
